apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portfolio-website-ingress
  namespace: portfolio-website
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  ingressClassName: nginx
  rules:
  - host: williamdoyle.co.uk
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: portfolio-website-service
            port:
              number: 80
  - host: www.williamdoyle.co.uk
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: portfolio-website-service
            port:
              number: 80

