apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portfolio-website-ingress
  namespace: portfolio-website
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - williamdoyle.co.uk
    - www.williamdoyle.co.uk
    secretName: portfolio-website-tls
  rules:
  - host: williamdoyle.co.uk
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: portfolio-website-service
            port:
              number: 80
  - host: www.williamdoyle.co.uk
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: portfolio-website-service
            port:
              number: 80

